### ISSUE TITLE
Todo list: operation translation V2

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#56]
After auto-generating clesperantoJ and pyclesperanto [compatibility lists](https://github.com/clij/assistant/commit/5d803702e83cf6509237c6c6028c93327e8b6c3d), I'm remaking the todo-list

closes https://github.com/clEsperanto/pyclesperanto_prototype/issues/15

# todos
- [x] add_images
- [x] affine_transform
- [ ] apply_vector_field
- [x] average_distance_of_n_closest_neighbors_map
- [x] average_neighbor_distance_map
- [x] centroids_of_background_and_labels
- [ ] closing_box
- [ ] closing_diamond
- [ ] cosinus
- [ ] count_non_zero_pixels
- [ ] count_non_zero_pixels2d_sphere
- [ ] count_non_zero_pixels_slice_by_slice_sphere
- [ ] count_non_zero_voxels3d_sphere
- [ ] cross_correlation
- [ ] cross_correlation
- [ ] custom_operation
- [ ] cylinder_transform
- [ ] detect_and_label_maxima
- [x] detect_minima_box
- [ ] draw_touch_count_mesh_between_touching_labels
- [ ] drift_correction_by_center_of_mass_fixation
- [ ] drift_correction_by_centroid_fixation
- [ ] entropy_box
- [ ] equalize_mean_intensities_of_slices
- [ ] euclidean_distance_from_label_centroid_map
- [ ] exclude_labels_on_surface
- [ ] exclude_labels_sub_surface
- [ ] extended_depth_of_focus_tenengrad_projection
- [ ] extended_depth_of_focus_variance_projection
- [ ] extended_depth_of_focus_variance_projection
- [ ] find_and_label_maxima
- [ ] find_maxima
- [ ] generate_distance_matrix_along_axis
- [ ] generate_jaccard_index_matrix
- [ ] generate_parametric_image
- [ ] generate_touch_count_matrix
- [ ] grey_level_atttribute_filtering
- [ ] image_to_stack
- [ ] intensity_correction
- [ ] intensity_correction_above_threshold_otsu
- [ ] label_maximum_extension_map
- [ ] label_maximum_extension_ratio_map
- [x] label_maximum_intensity_map
- [ ] label_mean_extension_map
- [x] label_mean_intensity_map
- [x] label_minimum_intensity_map
- [ ] label_standard_deviation_intensity_map
- [ ] label_surface
- [x] label_to_mask
- [ ] laplace_sphere
- [ ] local_maximum_average_distance_of_n_closest_neighbors_map
- [ ] local_maximum_average_neighbor_distance_map
- [x] local_maximum_touching_neighbor_count_map
- [ ] local_mean_average_distance_of_n_closest_neighbors_map
- [ ] local_mean_average_neighbor_distance_map
- [ ] local_mean_touch_portion_map
- [x] local_mean_touching_neighbor_count_map
- [ ] local_median_average_distance_of_n_closest_neighbors_map
- [ ] local_median_average_neighbor_distance_map
- [x] local_median_touching_neighbor_count_map
- [ ] local_minimum_average_distance_of_n_closest_neighbors_map
- [ ] local_minimum_average_neighbor_distance_map
- [x] local_minimum_touching_neighbor_count_map
- [ ] local_standard_deviation_average_distance_of_n_closest_neighbors_map
- [ ] local_standard_deviation_average_neighbor_distance_map
- [x] local_standard_deviation_touching_neighbor_count_map
- [ ] make_isotropic
- [ ] mask_stack_with_plane
- [ ] matrix_equal
- [x] maximum_distance_of_touching_neighbors
- [ ] maximum_of_masked_pixels
- [ ] maximum_z_projection_bounded
- [ ] mean_z_projection_bounded
- [x] merge_touching_labels
- [x] minimum_distance_of_touching_neighbors
- [ ] minimum_z_projection_bounded
- [ ] multiply_image_stack_with_scalars
- [ ] n_closest_distances
- [ ] non_local_means
- [ ] opening_box
- [ ] opening_diamond
- [ ] parametric_watershed
- [ ] reduce_labels_to_labelled_spots
- [ ] replace_pixels_if_zero
- [x] rigid_transform
- [x] rotate
- [ ] rotate_clockwise
- [ ] rotate_counter_clockwise
- [ ] set_random
- [ ] sobel_slice_by_slice
- [ ] sphere_transform
- [ ] stack_to_tiles
- [ ] standard_deviation_box
- [ ] standard_deviation_of_all_pixels
- [ ] standard_deviation_of_masked_pixels
- [ ] standard_deviation_sphere
- [x] statistics_of_image
- [ ] sum_image_slice_by_slice
- [ ] tenengrad
- [ ] tenengrad_fusion
- [ ] tenengrad_slice_by_slice
- [ ] threshold_default
- [ ] threshold_huang
- [ ] threshold_ij__iso_data
- [ ] threshold_intermodes
- [ ] threshold_iso_data
- [ ] threshold_li
- [ ] threshold_max_entropy
- [ ] threshold_mean
- [ ] threshold_min_error
- [ ] threshold_minimum
- [ ] threshold_moments
- [ ] threshold_percentile
- [ ] threshold_renyi_entropy
- [ ] threshold_shanbhag
- [ ] threshold_triangle
- [ ] threshold_yen
- [x] translate
- [ ] translation_registration
- [x] variance_box
- [ ] variance_of_all_pixels
- [ ] variance_of_masked_pixels
- [x] variance_sphere
- [ ] write_v_t_k_line_list_to_disc
- [x] z_position_of_maximum_z_projection
- [x] z_position_projection
- [x] z_position_range_projection

# missing aliases
For these operations, aliases should be defined to increase compatibility between Java and Python
- [x] average_distance_of_n_closest_points
- [x] average_distance_of_n_far_off_points
- [x] binary_union
- [x] binary_intersection
- [x] downsample_slice_by_slice_half_median

# to be discussed and / or deprecated
These operations existin in clij2/clijx and are eiter obsolete or very hard to implement on python side

- apply_weka_model
- apply_weka_to_table
- arg_maximum_z_projection
- automatic_threshold
- binary_fill_holes
- binary_fill_holes_slice_by_slice
- binary_weka_pixel_classifier
- capture_webcam_image
- convert_r_g_b_stack_to_gray_slice
- deformable_registration2d
- depth_color_projection
- distance_map
- draw_two_value_line
- extrema
- flood_fill_diamond
- gauss_jordan
- generate_feature_stack
- generate_grey_value_cooccurrence_matrix_box
- generate_integer_grey_value_cooccurrence_count_matrix_half_box
- generate_integer_grey_value_cooccurrence_count_matrix_half_diamond
- generate_label_feature_image
- generate_parametric_image_from_results_table_column
- get_automatic_threshold
- get_automatic_threshold
- get_bounding_box
- get_center_of_mass
- get_dimensions
- get_jaccard_index
- get_maximum_of_all_pixels
- get_mean_of_all_pixels
- get_mean_of_masked_pixels
- get_minimum_of_all_pixels
- get_sorensen_dice_coefficient
- get_sum_of_all_pixels
- label_voronoi_octagon
- local_extrema_box
- local_i_d
- local_threshold
- mean_closest_spot_distance
- mean_slice_by_slice_sphere
- mean_z_projection_above_threshold
- mean_z_projection_below_threshold
- median2d_box
- median2d_sphere
- median3d_box
- median3d_slice_by_slice_box
- median3d_slice_by_slice_sphere
- median3d_sphere
- median_z_projection
- merge_touching_labels_special
- minimum_z_projection_thresholded_bounded
- organise_windows
- particle_image_velocimetry
- particle_image_velocimetry2d
- particle_image_velocimetry_timelapse
- preload_from_disc
- presign
- print
- pull_as_r_o_i
- pull_labels_to_roilist
- pull_labels_to_roimanager
- pull_string
- pull_tile
- pull_to_results_table
- push_array
- push_results_table
- push_results_table_column
- push_string
- push_tile
- read_image_from_disc
- read_raw_image_from_disc
- reslice_bottom
- reslice_left
- reslice_radial
- reslice_radial
- reslice_radial
- reslice_right
- reslice_top
- results_table_column_to_image
- save_as_tif
- save_as_t_i_f
- scale
- scale2d
- start_continuous_webcam_acquisition
- stop_continuous_webcam_acquisition
- stop_watch
- subtract_background
- threshold
- threshold_dog
- top_hat_octagon
- top_hat_octagon_slice_by_slice
- train_auto_context_weka_model_with_options
- train_weka_from_table
- train_weka_model
- train_weka_model_with_options
- translation_timelapse_registration
- voronoi_octagon
- watershed
- weka_label_classifier
